version: '3'
services:
  app:
    image: vladimir226/vlahasher:latest
    ports:
      - 8080:8080



name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Run Flake8
      run: flake8

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: vladimir226/vlahasher:latest
    - name: Deploy Application
      run: docker-compose up -d
