name: Docker Build 

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository  # Шаг: Клонирование репозитория
      uses: actions/checkout@v2  
      
    - name: Run Flake8  # Шаг: Запуск Flake8
      run: |
        pip install flake8  # Установка и запуск Flake8
        flake8

    - name: Set up Docker  # Шаг: Настройка Docker
      uses: docker/setup-buildx-action@v1  
      
    - name: Log in to Docker Hub  # Шаг: Вход в Docker Hub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Имя пользователя Docker Hub
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Токен Docker Hub

    - name: Build and push Docker image  # Шаг: Сборка и публикация Docker-образа
      uses: docker/build-push-action@v2 
      with:
        context: .  # Контекст сборки - текущая директория
        push: true  # Публикация собранного образа
        tags: vladimir226/vlahasher:latest 

#вроде как не работает, не смог найстроить
    - name: Deploy to local machine  # Шаг: Развёртывание на локальной машине (Не успех)
      run: docker-compose up -d  
