name: Docker Build  # Название workflow

on:
  push:
    branches:
      - main  # Действие, которое запускает workflow - пуш в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Запуск на Ubuntu

    steps:
    - name: Checkout repository  # Шаг: Клонирование репозитория
      uses: actions/checkout@v2  # Использование готового действия для клонирования репозитория
      
    - name: Run Flake8  # Шаг: Запуск Flake8
      run: |
        pip install flake8  # Установка Flake8
        flake8  # Запуск Flake8 для проверки стиля кода

    - name: Set up Docker  # Шаг: Настройка Docker
      uses: docker/setup-buildx-action@v1  # Использование готового действия для настройки Docker Buildx
      
    - name: Log in to Docker Hub  # Шаг: Вход в Docker Hub
      uses: docker/login-action@v1  # Использование готового действия для входа в Docker Hub
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Имя пользователя Docker Hub, хранящееся в секретах репозитория
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Токен Docker Hub, хранящийся в секретах репозитория

    - name: Build and push Docker image  # Шаг: Сборка и публикация Docker-образа
      uses: docker/build-push-action@v2  # Использование готового действия для сборки и публикации Docker-образа
      with:
        context: .  # Контекст сборки - текущая директория
        push: true  # Публикация собранного образа
        tags: vladimir226/vlahasher:latest  # Теги для образа

    - name: Deploy to local machine  # Шаг: Развёртывание на локальной машине
      run: docker-compose up -d  # Запуск команды docker-compose для развёртывания контейнеров в фоновом режиме